version: "3"

services:
  jekyll:
      image: jekyll/jekyll:latest
      command: jekyll serve --livereload --host "0.0.0.0"
      ports:
        - 4000:4000
        - 35729:35729
      volumes:
        - .:/srv/jekyll